In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('shapes.jpg')
imgContour = img.copy()

## Contour or Edge Detection

In [3]:
imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGray, (7,7), 1)

In [4]:
imgCanny = cv2.Canny(imgBlur, 50,50) # threshold

In [5]:
cv2.imshow('Image', imgCanny)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
# Blank Image
imgBlank = np.zeros_like(img)

In [7]:
def getContours(img):
    # retrieval methods: cv2.RETR_EXTERNAL ==> It retrieves the external contours
    contours, hierarchy = cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE) 
    for cnt in contours:
        area = cv2.contourArea(cnt)
        #print(area)
        cv2.drawContours(imgContour, cnt, -1, (255,0,0), 3)
        perimeter = cv2.arcLength(cnt, True) # True: shapes are 
        #print(perimeter)
        approx = cv2.approxPolyDP(cnt, 0.02 * perimeter, True)
        # no. of verticies/object corners of each shape
        print(approx)
        #print(len(approx))
        objCorners = len(approx)
        # bounding box arround the objects
        x,y,w,h = cv2.boundingRect(approx)
        if objCorners == 3: 
            objectType = "Triangle"
        elif objCorners == 4:
            aspRatio = w/float(h)
            if aspRatio > 0.95 and aspRatio < 1.05:
                objectType = "Square"
            else:
                objectType = "Rectangle"
        elif objCorners > 4:
            objectType = "Circle"
        else : 
            objectType = "None"
        cv2.rectangle(imgContour, (x,y), (x+w, y+h), (0,255,0), 2)
        cv2.putText(imgContour, objectType, (x+(w//2)-10, y+(h//2)-10), cv2.FONT_HERSHEY_COMPLEX, 0.5, (255,255,0), 2)

In [8]:
getContours(imgCanny)

[[[149 248]]

 [[104 273]]

 [[ 92 316]]

 [[117 359]]

 [[166 371]]

 [[208 348]]

 [[221 300]]

 [[196 260]]]
[[[419 237]]

 [[419 371]]

 [[614 371]]

 [[613 236]]]
[[[528 151]]

 [[675 153]]

 [[602  49]]]
[[[153  49]]

 [[153 189]]

 [[300 189]]

 [[300  49]]]


In [126]:
cv2.imshow('Contour Image', imgContour)
cv2.waitKey()
cv2.destroyAllWindows()