In [27]:
marks = [60, 20, 70, 80]
hours = [6, 2, 7, 8]

In [28]:
import numpy as np

In [29]:
marks = np.array(marks)
hours = np.array(hours)

In [30]:
hours.shape

(4,)

In [31]:
hours

array([6, 2, 7, 8])

In [32]:
hours = hours.reshape(-1, 1)

In [33]:
hours.shape

(4, 1)

In [34]:
hours

array([[6],
       [2],
       [7],
       [8]])

In [35]:
from sklearn.loggingnear_model import LinearRegression

In [36]:
mind = LinearRegression()

In [37]:
mind.fit(hours, marks)

LinearRegression()

In [38]:
mind.predict([[9]])

array([90.])