In [1]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv('Salary_Data.csv')

In [4]:
dataset.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [5]:
dataset.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [6]:
y = dataset['Salary']
x = dataset['YearsExperience']

In [7]:
type(x)

pandas.core.series.Series

In [8]:
# converting pandas series to numpy array datatype for the fit() method
x = x.values

In [9]:
type(x)

numpy.ndarray

In [10]:
x.shape

(30,)

In [11]:
# converting x from 1D to 2D numpy array
x = x.reshape(-1,1)

In [12]:
x.shape

(30, 1)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [15]:
X_train.shape

(20, 1)

In [16]:
y_train.shape

(20,)

## Linear Regression : y = b + c*x

##### b --> bias / Y-intercept
#####    c --> coefficient
      

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model = LinearRegression()

In [19]:
model.fit(X_train, y_train)

LinearRegression()

In [20]:
model.predict([[9.6]])

array([115814.30756236])

In [21]:
y_test

27    112635.0
15     67938.0
23    113812.0
17     83088.0
8      64445.0
9      57189.0
28    122391.0
24    109431.0
12     56957.0
0      39343.0
Name: Salary, dtype: float64

In [22]:
model.predict(X_test)

array([115814.30756236,  71511.92534771, 102617.85328566,  75282.34085534,
        55487.65944028,  60200.67882482, 122412.53470072, 107330.8726702 ,
        63028.49045554,  35692.97802523])

LinearRegression()

In [23]:
# joblib module is used to save and load the model
import joblib

In [24]:
joblib.dump(model,'salarymodel2.pk1')

['salarymodel2.pk1']

In [29]:
experience_yrs = 7.1

In [31]:
salary_pred = model.predict([[experience_yrs]])

In [32]:
salary_pred

array([92886.932681])

In [33]:
model.coef_

array([9449.96232146])

In [34]:
model.intercept_

25792.20019866871